export const summonBlock: string;
export const summonName: string;
export const typeLine: string;
export const featureName: string;
export const abilityScoreTable: string;
export const abilityScore: string;
export const sectionDivider: string;
export const statList: string;
export const statName: string;
export const feature: string;
export const attackType: string;
export const hit: string;
export const source: string;
interface Namespace {
  summonBlock: string;
  'summon-block': string;
  summonName: string;
  'summon-name': string;
  typeLine: string;
  'type-line': string;
  featureName: string;
  'feature-name': string;
  abilityScoreTable: string;
  'ability-score-table': string;
  abilityScore: string;
  'ability-score': string;
  sectionDivider: string;
  'section-divider': string;
  statList: string;
  'stat-list': string;
  statName: string;
  'stat-name': string;
  feature: string;
  attackType: string;
  'attack-type': string;
  hit: string;
  source: string;
}
declare const summonBlockScss: Namespace;
export default summonBlockScss;
